### ISSUE TITLE
generate static site

### ISSUE THREAD

**Issue by capsulecorplab** [LearnTeachCode/code-coffee-compendium#36]
Options:

Jekyll
https://github.com/asciidoctor/jekyll-asciidoc
https://github.com/asciidoctor/jekyll-asciidoc-quickstart

Antora
https://docs.antora.org/antora/2.1/run-antora/

**Comment by gaurav-nelson** [comment]
You can use Travis CI to publish to GitHub pages.

Use following `.tavis.yml` file
```yaml
language: ruby
before_install:
  - gem install asciidoctor
script: asciidoctor --destination-dir=build README.adoc --out-file=index.html
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository on Travis CI webpage, as a secure variable
  local_dir: build
  keep_history: true
  on:
    branch: master 
```
